name: Loren Cotter
favicon: null
layout_spectrum: 0.80195
typography_spectrum: 0.15943
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ce9276'
    - '#232319'
    - '#383732'
    - '#675143'
    - '#5c2f1c'
  brandStrength: 0.625
  lightness: 0.8844308445695788
  saturation: 0.3595886775292456
  rhythmicContrast: 0.0095067392103374
purpose: []
