name: Loren Cotter
favicon: null
layout_spectrum: 0.82053
typography_spectrum: 0.19949
title: 'Travel + Work '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fe3023'
    - '#fe8e0e'
    - '#3e150f'
    - '#0568bd'
    - '#caf2fe'
  brandStrength: 0.625
  lightness: 0.6875
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
