name: Loren Cotter
favicon: null
layout_spectrum: 0.82053
typography_spectrum: 0.19949
title: 'Portfolio '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050205'
    - '#cf0000'
    - '#ffffff'
    - '#584c41'
    - '#f24c30'
  brandStrength: 0.5625
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
