name: Loren Cotter
favicon: null
layout_spectrum: 0.82554
typography_spectrum: 0.39149
title: 'Loren Cotter // Travel + Work '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8b8b89'
    - '#4b4744'
    - '#bec2c5'
    - '#feffff'
    - '#e43697'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
