name: Loren Cotter
favicon: null
layout_spectrum: 0.62187
typography_spectrum: 0.39149
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d2d4d1'
    - '#8aaebe'
    - '#3a6e84'
    - '#33313c'
    - '#9d928e'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
