name: Loren Cotter
favicon: null
layout_spectrum: 0.1828
typography_spectrum: 0.39149
title: 'Loren Cotter // Travel + Work '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#979795'
    - '#b2bdc5'
    - '#000000'
    - '#543430'
    - '#f94578'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
