name: Loren Cotter
favicon: null
layout_spectrum: 0.82053
typography_spectrum: 0.61685
title: 'Portfolio '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ce9276'
    - '#232319'
    - '#383732'
    - '#675143'
    - '#5c2f1c'
  brandStrength: 0.5625
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
