name: Loren Cotter
favicon: null
layout_spectrum: 1
typography_spectrum: 0.19949
title: 'Loren Cotter // Travel + Work '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5e2e3'
    - '#1b1b1b'
    - '#bf0000'
    - '#6e653d'
    - '#eb6d89'
  brandStrength: 0.4375
  lightness: 0.75
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
